waypoints:
  - name: wp1
    pose:
      x: 1.0
      y: 0.0
      yaw: 0.0
  - name: wp2
    pose:
      x: 2.0
      y: 1.0
      yaw: 1.57
  - name: wp3
    pose:
      x: 3.0
      y: 1.0
      yaw: 0.0
