object_perception_lidar_node:
  ros__parameters:
    scan_topic: /scan
    cmd_vel_topic: /cmd_vel

    front_angle_deg: 30.0
    min_range_m: 0.12
    obstacle_range_m: 0.70

    use_map_filter: true
    map_topic: /map
    map_frame: map
    laser_frame: ""

    occupied_threshold: 50
    map_inflation_m: 0.20
    treat_unknown_as_occupied: true

    clear_confirm_sec: 0.6
    stop_publish_hz: 10.0

    telegram_enable: false
    telegram_prefix: "[LIMO]"
